/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicationsIndexRouteImport } from './routes/publications/index'
import { Route as LegaldocsIndexRouteImport } from './routes/legaldocs/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as ContactusIndexRouteImport } from './routes/contactus/index'
import { Route as BlogsIndexRouteImport } from './routes/blogs/index'
import { Route as AboutusIndexRouteImport } from './routes/aboutus/index'
import { Route as PublicationsSlugIndexRouteImport } from './routes/publications/$slug/index'
import { Route as EventsPreviousseminarsIndexRouteImport } from './routes/events/previousseminars/index'
import { Route as EventsPreviousfoodservicesIndexRouteImport } from './routes/events/previousfoodservices/index'
import { Route as EventsPreviouscongregationsIndexRouteImport } from './routes/events/previouscongregations/index'
import { Route as BlogsBlogIdIndexRouteImport } from './routes/blogs/$blogId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationsIndexRoute = PublicationsIndexRouteImport.update({
  id: '/publications/',
  path: '/publications/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegaldocsIndexRoute = LegaldocsIndexRouteImport.update({
  id: '/legaldocs/',
  path: '/legaldocs/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactusIndexRoute = ContactusIndexRouteImport.update({
  id: '/contactus/',
  path: '/contactus/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutusIndexRoute = AboutusIndexRouteImport.update({
  id: '/aboutus/',
  path: '/aboutus/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationsSlugIndexRoute = PublicationsSlugIndexRouteImport.update({
  id: '/publications/$slug/',
  path: '/publications/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsPreviousseminarsIndexRoute =
  EventsPreviousseminarsIndexRouteImport.update({
    id: '/events/previousseminars/',
    path: '/events/previousseminars/',
    getParentRoute: () => rootRouteImport,
  } as any)
const EventsPreviousfoodservicesIndexRoute =
  EventsPreviousfoodservicesIndexRouteImport.update({
    id: '/events/previousfoodservices/',
    path: '/events/previousfoodservices/',
    getParentRoute: () => rootRouteImport,
  } as any)
const EventsPreviouscongregationsIndexRoute =
  EventsPreviouscongregationsIndexRouteImport.update({
    id: '/events/previouscongregations/',
    path: '/events/previouscongregations/',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogsBlogIdIndexRoute = BlogsBlogIdIndexRouteImport.update({
  id: '/blogs/$blogId/',
  path: '/blogs/$blogId/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aboutus': typeof AboutusIndexRoute
  '/blogs': typeof BlogsIndexRoute
  '/contactus': typeof ContactusIndexRoute
  '/events': typeof EventsIndexRoute
  '/legaldocs': typeof LegaldocsIndexRoute
  '/publications': typeof PublicationsIndexRoute
  '/blogs/$blogId': typeof BlogsBlogIdIndexRoute
  '/events/previouscongregations': typeof EventsPreviouscongregationsIndexRoute
  '/events/previousfoodservices': typeof EventsPreviousfoodservicesIndexRoute
  '/events/previousseminars': typeof EventsPreviousseminarsIndexRoute
  '/publications/$slug': typeof PublicationsSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aboutus': typeof AboutusIndexRoute
  '/blogs': typeof BlogsIndexRoute
  '/contactus': typeof ContactusIndexRoute
  '/events': typeof EventsIndexRoute
  '/legaldocs': typeof LegaldocsIndexRoute
  '/publications': typeof PublicationsIndexRoute
  '/blogs/$blogId': typeof BlogsBlogIdIndexRoute
  '/events/previouscongregations': typeof EventsPreviouscongregationsIndexRoute
  '/events/previousfoodservices': typeof EventsPreviousfoodservicesIndexRoute
  '/events/previousseminars': typeof EventsPreviousseminarsIndexRoute
  '/publications/$slug': typeof PublicationsSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aboutus/': typeof AboutusIndexRoute
  '/blogs/': typeof BlogsIndexRoute
  '/contactus/': typeof ContactusIndexRoute
  '/events/': typeof EventsIndexRoute
  '/legaldocs/': typeof LegaldocsIndexRoute
  '/publications/': typeof PublicationsIndexRoute
  '/blogs/$blogId/': typeof BlogsBlogIdIndexRoute
  '/events/previouscongregations/': typeof EventsPreviouscongregationsIndexRoute
  '/events/previousfoodservices/': typeof EventsPreviousfoodservicesIndexRoute
  '/events/previousseminars/': typeof EventsPreviousseminarsIndexRoute
  '/publications/$slug/': typeof PublicationsSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aboutus'
    | '/blogs'
    | '/contactus'
    | '/events'
    | '/legaldocs'
    | '/publications'
    | '/blogs/$blogId'
    | '/events/previouscongregations'
    | '/events/previousfoodservices'
    | '/events/previousseminars'
    | '/publications/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aboutus'
    | '/blogs'
    | '/contactus'
    | '/events'
    | '/legaldocs'
    | '/publications'
    | '/blogs/$blogId'
    | '/events/previouscongregations'
    | '/events/previousfoodservices'
    | '/events/previousseminars'
    | '/publications/$slug'
  id:
    | '__root__'
    | '/'
    | '/aboutus/'
    | '/blogs/'
    | '/contactus/'
    | '/events/'
    | '/legaldocs/'
    | '/publications/'
    | '/blogs/$blogId/'
    | '/events/previouscongregations/'
    | '/events/previousfoodservices/'
    | '/events/previousseminars/'
    | '/publications/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutusIndexRoute: typeof AboutusIndexRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
  ContactusIndexRoute: typeof ContactusIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  LegaldocsIndexRoute: typeof LegaldocsIndexRoute
  PublicationsIndexRoute: typeof PublicationsIndexRoute
  BlogsBlogIdIndexRoute: typeof BlogsBlogIdIndexRoute
  EventsPreviouscongregationsIndexRoute: typeof EventsPreviouscongregationsIndexRoute
  EventsPreviousfoodservicesIndexRoute: typeof EventsPreviousfoodservicesIndexRoute
  EventsPreviousseminarsIndexRoute: typeof EventsPreviousseminarsIndexRoute
  PublicationsSlugIndexRoute: typeof PublicationsSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publications/': {
      id: '/publications/'
      path: '/publications'
      fullPath: '/publications'
      preLoaderRoute: typeof PublicationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legaldocs/': {
      id: '/legaldocs/'
      path: '/legaldocs'
      fullPath: '/legaldocs'
      preLoaderRoute: typeof LegaldocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contactus/': {
      id: '/contactus/'
      path: '/contactus'
      fullPath: '/contactus'
      preLoaderRoute: typeof ContactusIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aboutus/': {
      id: '/aboutus/'
      path: '/aboutus'
      fullPath: '/aboutus'
      preLoaderRoute: typeof AboutusIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publications/$slug/': {
      id: '/publications/$slug/'
      path: '/publications/$slug'
      fullPath: '/publications/$slug'
      preLoaderRoute: typeof PublicationsSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/previousseminars/': {
      id: '/events/previousseminars/'
      path: '/events/previousseminars'
      fullPath: '/events/previousseminars'
      preLoaderRoute: typeof EventsPreviousseminarsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/previousfoodservices/': {
      id: '/events/previousfoodservices/'
      path: '/events/previousfoodservices'
      fullPath: '/events/previousfoodservices'
      preLoaderRoute: typeof EventsPreviousfoodservicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/previouscongregations/': {
      id: '/events/previouscongregations/'
      path: '/events/previouscongregations'
      fullPath: '/events/previouscongregations'
      preLoaderRoute: typeof EventsPreviouscongregationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/$blogId/': {
      id: '/blogs/$blogId/'
      path: '/blogs/$blogId'
      fullPath: '/blogs/$blogId'
      preLoaderRoute: typeof BlogsBlogIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutusIndexRoute: AboutusIndexRoute,
  BlogsIndexRoute: BlogsIndexRoute,
  ContactusIndexRoute: ContactusIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  LegaldocsIndexRoute: LegaldocsIndexRoute,
  PublicationsIndexRoute: PublicationsIndexRoute,
  BlogsBlogIdIndexRoute: BlogsBlogIdIndexRoute,
  EventsPreviouscongregationsIndexRoute: EventsPreviouscongregationsIndexRoute,
  EventsPreviousfoodservicesIndexRoute: EventsPreviousfoodservicesIndexRoute,
  EventsPreviousseminarsIndexRoute: EventsPreviousseminarsIndexRoute,
  PublicationsSlugIndexRoute: PublicationsSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
